// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxRn1p6Wpe6B_4MGxpT2CwmuG9B9db7w',
    appId: '1:527654279314:web:1d0c0883aea6e35ad2ee4b',
    messagingSenderId: '527654279314',
    projectId: 'meetoplay-91a7d',
    authDomain: 'meetoplay-91a7d.firebaseapp.com',
    storageBucket: 'meetoplay-91a7d.appspot.com',
    measurementId: 'G-F2RVRZVSFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr93mJ9McRMqPS86CD3BnxWzJvbXsr3Aw',
    appId: '1:527654279314:android:024c149a56ff11a1d2ee4b',
    messagingSenderId: '527654279314',
    projectId: 'meetoplay-91a7d',
    storageBucket: 'meetoplay-91a7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKnGeeCT0nBZfTAfy4tQmiG_34OFqE5KA',
    appId: '1:527654279314:ios:50a7bed4568f8a86d2ee4b',
    messagingSenderId: '527654279314',
    projectId: 'meetoplay-91a7d',
    storageBucket: 'meetoplay-91a7d.appspot.com',
    iosBundleId: 'com.example.meetoplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKnGeeCT0nBZfTAfy4tQmiG_34OFqE5KA',
    appId: '1:527654279314:ios:50a7bed4568f8a86d2ee4b',
    messagingSenderId: '527654279314',
    projectId: 'meetoplay-91a7d',
    storageBucket: 'meetoplay-91a7d.appspot.com',
    iosBundleId: 'com.example.meetoplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdxRn1p6Wpe6B_4MGxpT2CwmuG9B9db7w',
    appId: '1:527654279314:web:96ecba8944caac91d2ee4b',
    messagingSenderId: '527654279314',
    projectId: 'meetoplay-91a7d',
    authDomain: 'meetoplay-91a7d.firebaseapp.com',
    storageBucket: 'meetoplay-91a7d.appspot.com',
    measurementId: 'G-N9HCZGQN3R',
  );

}